#!/opt/pwn.college/bash

PATH_TO_FILE="$1"

if [[ ! -f $PATH_TO_FILE ]]; then
  echo "Please enter a valid path!"
  exit 1
fi

if cat "$PATH_TO_FILE" > /dev/null; then
  echo "I managed to read your file..."
else
  echo "Success! Here's your flag: "
  /bin/cat /flag
fi
